version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 1024
    cooldown:
      default-days: 7

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/New_York"
    allow:
      # Also update indirect dependencies
      - dependency-type: all
    open-pull-requests-limit: 1024
    cooldown:
      exclude:
        - asn1
        - asn1-derive
        - openssl
        - openssl-macros
        - openssl-sys
        - pyo3
        - pyo3-build-config
        - pyo3-ffi
        - pyo3-macros
        - pyo3-macros-backend

  - package-ecosystem: uv
    directories:
      - "/"
      - "/.github/requirements/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/New_York"
    allow:
      # Also update indirect dependencies
      - dependency-type: all
    open-pull-requests-limit: 1024
    cooldown:
      exclude:
        - coverage
        - mypy
        - nox
        - pytest
        - pytest-benchmark
        - pytest-cov
        - pytest-randomly
        - pytest-xdist
        - ruff
        - uv
        - cffi
        - maturin
