[workspace]
resolver = "2"
members = [
    "src/rust/",
    "src/rust/cryptography-cffi",
    "src/rust/openssl-bridge",
    "src/rust/openssl-bridge-sys",
    "src/rust/cryptography-crypto",
    "src/rust/cryptography-keepalive",
    "src/rust/cryptography-key-parsing",
    "src/rust/cryptography-x509",
    "src/rust/cryptography-x509-verification",
]

[workspace.package]
version = "0.51.0-dev1"
authors = ["The cryptography developers <cryptography-dev@python.org>"]
edition = "2021"
publish = false
# This specifies the MSRV
rust-version = "1.83.0"
license = "Apache-2.0 OR BSD-3-Clause"

[workspace.dependencies]
openssl-bridge-sys = { path = "src/rust/openssl-bridge-sys" }
openssl-bridge = { path = "src/rust/openssl-bridge" }
asn1 = { version = "0.24.1", default-features = false }
base64 = "0.23"
cc = "1.2.63"
cfg-if = "1"
pem = { version = "4", default-features = false }
pyo3 = { version = "0.29", features = ["abi3", "abi3t"] }
pyo3-build-config = { version = "0.29" }
self_cell = "1"

[profile.release]
overflow-checks = true
