TYPES = [
    'static const int NID_undef;',
    'static const int NID_dsa;',
    'static const int NID_dsaWithSHA;',
    'static const int NID_dsaWithSHA1;',
#   'static const int NID_md2;',
    'static const int NID_md4;',
    'static const int NID_md5;',
    'static const int NID_mdc2;',
    'static const int NID_ripemd160;',
    'static const int NID_sha;',
    'static const int NID_sha1;',
    'static const int NID_sha256;',
    'static const int NID_sha384;',
    'static const int NID_sha512;',
    'static const int NID_sha224;',
    'static const int NID_sha;',
    'static const int NID_ecdsa_with_SHA1;',
    'static const int NID_ecdsa_with_SHA224;',
    'static const int NID_ecdsa_with_SHA256;',
    'static const int NID_ecdsa_with_SHA384;',
    'static const int NID_ecdsa_with_SHA512;',
]
