# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

from cryptography.hazmat.primitives.asymmetric import ec

class ECPrivateKey: ...
class ECPublicKey: ...

def curve_supported(curve: ec.EllipticCurve) -> bool: ...
def private_key_from_ptr(ptr: int) -> ec.EllipticCurvePrivateKey: ...
def public_key_from_ptr(ptr: int) -> ec.EllipticCurvePublicKey: ...
def generate_private_key(
    curve: ec.EllipticCurve,
) -> ec.EllipticCurvePrivateKey: ...
def from_private_numbers(
    numbers: ec.EllipticCurvePrivateNumbers,
) -> ec.EllipticCurvePrivateKey: ...
def from_public_numbers(
    numbers: ec.EllipticCurvePublicNumbers,
) -> ec.EllipticCurvePublicKey: ...
def from_public_bytes(
    curve: ec.EllipticCurve, data: bytes
) -> ec.EllipticCurvePublicKey: ...
def derive_private_key(
    private_value: int, curve: ec.EllipticCurve
) -> ec.EllipticCurvePrivateKey: ...
