# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

from cryptography.hazmat.primitives.asymmetric import mldsa
from cryptography.utils import Buffer

class MlDsa65PrivateKey: ...
class MlDsa65PublicKey: ...

def generate_mldsa65_key() -> mldsa.MlDsa65PrivateKey: ...
def from_mldsa65_public_bytes(data: bytes) -> mldsa.MlDsa65PublicKey: ...
def from_mldsa65_seed_bytes(data: Buffer) -> mldsa.MlDsa65PrivateKey: ...
