# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

from cryptography.hazmat.primitives.asymmetric import mldsa
from cryptography.utils import Buffer

class MlDsa44PrivateKey: ...
class MlDsa44PublicKey: ...
class MlDsa65PrivateKey: ...
class MlDsa65PublicKey: ...

def generate_key() -> mldsa.MlDsa44PrivateKey | mldsa.MlDsa65PrivateKey: ...
def from_public_bytes(
    data: bytes,
) -> mldsa.MlDsa44PublicKey | mldsa.MlDsa65PublicKey: ...
def from_seed_bytes(
    data: Buffer,
) -> mldsa.MlDsa44PrivateKey | mldsa.MlDsa65PrivateKey: ...
