# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

from cryptography.hazmat.primitives.asymmetric import mlkem
from cryptography.utils import Buffer

class MLKEM768X25519PrivateKey: ...
class MLKEM768X25519PublicKey: ...

def generate_key() -> mlkem.MLKEM768X25519PrivateKey: ...
def from_seed_bytes(data: Buffer) -> mlkem.MLKEM768X25519PrivateKey: ...
def from_public_bytes(data: Buffer) -> mlkem.MLKEM768X25519PublicKey: ...
