# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

from __future__ import absolute_import, division, print_function

INCLUDES = """
#include <openssl/opensslv.h>


#if defined(LIBRESSL_VERSION_NUMBER)
#define CRYPTOGRAPHY_IS_LIBRESSL 1
#define CRYPTOGRAPHY_LIBRESSL_270_OR_GREATER \
    LIBRESSL_VERSION_NUMBER >= 0x20700000
#define CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270 \
    LIBRESSL_VERSION_NUMBER < 0x20700000
#define CRYPTOGRAPHY_LIBRESSL_LESS_THAN_251 \
    LIBRESSL_VERSION_NUMBER < 0x20501000
#define CRYPTOGRAPHY_LIBRESSL_LESS_THAN_250 \
    LIBRESSL_VERSION_NUMBER < 0x20500000
#else
#define CRYPTOGRAPHY_IS_LIBRESSL 0
#define CRYPTOGRAPHY_LIBRESSL_270_OR_GREATER 0
#define CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270 0
#define CRYPTOGRAPHY_LIBRESSL_LESS_THAN_251 0
#define CRYPTOGRAPHY_LIBRESSL_LESS_THAN_250 0
#endif

/*
    LibreSSL removed e_os2.h from the public headers so we'll only include it
    if we're using vanilla OpenSSL.
*/
#if !CRYPTOGRAPHY_IS_LIBRESSL
#include <openssl/e_os2.h>
#endif
#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <Wincrypt.h>
#include <Winsock2.h>
#endif

#define CRYPTOGRAPHY_OPENSSL_102_OR_GREATER \
    (OPENSSL_VERSION_NUMBER >= 0x10002000 && !CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)
#define CRYPTOGRAPHY_OPENSSL_102L_OR_GREATER \
    (OPENSSL_VERSION_NUMBER >= 0x100020cf && !CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)
#define CRYPTOGRAPHY_OPENSSL_110_OR_GREATER \
    (OPENSSL_VERSION_NUMBER >= 0x10100000 && !CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)
#define CRYPTOGRAPHY_OPENSSL_110F_OR_GREATER \
    (OPENSSL_VERSION_NUMBER >= 0x1010006f && !CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)

#define CRYPTOGRAPHY_OPENSSL_LESS_THAN_102 \
    (OPENSSL_VERSION_NUMBER < 0x10002000 || CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)
#define CRYPTOGRAPHY_OPENSSL_LESS_THAN_102I \
    (OPENSSL_VERSION_NUMBER < 0x1000209f || CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)
#define CRYPTOGRAPHY_OPENSSL_LESS_THAN_110 \
    (OPENSSL_VERSION_NUMBER < 0x10100000 || CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)
#define CRYPTOGRAPHY_OPENSSL_LESS_THAN_110PRE4 \
    (OPENSSL_VERSION_NUMBER < 0x10100004 || CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)
#define CRYPTOGRAPHY_OPENSSL_LESS_THAN_110PRE5 \
    (OPENSSL_VERSION_NUMBER < 0x10100005 || CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)
#define CRYPTOGRAPHY_OPENSSL_LESS_THAN_110PRE6 \
    (OPENSSL_VERSION_NUMBER < 0x10100006 || CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270)
"""

TYPES = """
static const int CRYPTOGRAPHY_OPENSSL_102L_OR_GREATER;
static const int CRYPTOGRAPHY_OPENSSL_110_OR_GREATER;
static const int CRYPTOGRAPHY_OPENSSL_110F_OR_GREATER;

static const int CRYPTOGRAPHY_OPENSSL_LESS_THAN_102I;
static const int CRYPTOGRAPHY_OPENSSL_LESS_THAN_102;

static const int CRYPTOGRAPHY_IS_LIBRESSL;
static const int CRYPTOGRAPHY_LIBRESSL_270_OR_GREATER;
static const int CRYPTOGRAPHY_LIBRESSL_LESS_THAN_270;
static const int CRYPTOGRAPHY_LIBRESSL_LESS_THAN_251;
static const int CRYPTOGRAPHY_LIBRESSL_LESS_THAN_250;
"""

FUNCTIONS = """
"""

CUSTOMIZATIONS = """
"""
