import typing

from cryptography.x509 import TLSFeature, PrecertPoison

def decode_dss_signature(signature: bytes) -> typing.Tuple[int, int]: ...
def encode_dss_signature(r: int, s: int) -> bytes: ...
def parse_tls_feature(data: bytes) -> TLSFeature: ...
def parse_precert_poison(data: bytes) -> PrecertPoison: ...
def parse_spki_for_data(data: bytes) -> bytes: ...
