# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

import typing

from cryptography.utils import Buffer

class SeekableReader(typing.Protocol):
    """The minimal binary file-like interface ``decrypt_range`` requires.

    Only ``seek`` and ``read`` are used; an implementation need not provide
    anything else. ``mmap.mmap`` and files opened in binary mode satisfy this,
    as does a small adapter that fetches byte ranges from remote storage.
    """

    def seek(self, offset: int, whence: int = ..., /) -> object: ...
    def read(self, size: int, /) -> bytes: ...

class Cobblestone128Encryptor:
    def __init__(self, key: Buffer, context: Buffer) -> None: ...
    @staticmethod
    def generate_key() -> bytes: ...
    def update(self, data: Buffer) -> bytes: ...
    def update_into(self, data: Buffer, buf: Buffer) -> int: ...
    def finalize(self) -> bytes: ...

class Cobblestone128Decryptor:
    def __init__(self, key: Buffer, context: Buffer) -> None: ...
    def update(self, data: Buffer) -> bytes: ...
    def update_into(self, data: Buffer, buf: Buffer) -> int: ...
    def finalize(self) -> bytes: ...
    def decrypt_range(
        self,
        source: Buffer | SeekableReader,
        offset: int,
        length: int,
    ) -> bytes: ...

class Cobblestone256Encryptor:
    def __init__(self, key: Buffer, context: Buffer) -> None: ...
    @staticmethod
    def generate_key() -> bytes: ...
    def update(self, data: Buffer) -> bytes: ...
    def update_into(self, data: Buffer, buf: Buffer) -> int: ...
    def finalize(self) -> bytes: ...

class Cobblestone256Decryptor:
    def __init__(self, key: Buffer, context: Buffer) -> None: ...
    def update(self, data: Buffer) -> bytes: ...
    def update_into(self, data: Buffer, buf: Buffer) -> int: ...
    def finalize(self) -> bytes: ...
    def decrypt_range(
        self,
        source: Buffer | SeekableReader,
        offset: int,
        length: int,
    ) -> bytes: ...
