# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

class NativeError(Exception): ...
class VerificationError(Exception): ...

FILETYPE_PEM: int
FILETYPE_ASN1: int
TYPE_RSA: int
TYPE_DSA: int
TYPE_DH: int
TYPE_EC: int
CRL_CHECK: int
CRL_CHECK_ALL: int
IGNORE_CRITICAL: int
X509_STRICT: int
ALLOW_PROXY_CERTS: int
POLICY_CHECK: int
EXPLICIT_POLICY: int
INHIBIT_MAP: int
CHECK_SS_SIGNATURE: int
PARTIAL_CHAIN: int

def curve_names() -> list[str]: ...
def legacy_dsa_private_key_der(bits: int) -> bytes: ...
def private_key_pem(
    der: bytes, cipher: bytes | None = None, password: bytes | None = None
) -> bytes: ...
def rsa_private_key_text(der: bytes) -> bytes: ...

class Name:
    def __init__(self) -> None: ...
    @staticmethod
    def from_der(der: bytes) -> Name: ...
    def copy(self) -> Name: ...
    def der(self) -> bytes: ...
    def set(self, attribute: bytes, value: bytes) -> None: ...
    def get(self, attribute: bytes) -> str | None: ...
    def components(self) -> list[tuple[bytes, bytes]]: ...
    def compare(self, other: Name) -> int: ...
    def hash(self) -> int: ...
    def display(self) -> str: ...

class Certificate:
    def __init__(self) -> None: ...
    @staticmethod
    def decode(data: bytes, format: int) -> Certificate: ...
    def encode(self, format: int) -> bytes: ...
    def version(self) -> int: ...
    def set_version(self, version: int) -> None: ...
    def name(self, issuer: bool) -> Name: ...
    def set_name(self, issuer: bool, name: Name) -> None: ...
    def set_name_attribute(
        self, issuer: bool, attribute: bytes, value: bytes
    ) -> None: ...
    def public_key_der(self) -> bytes: ...
    def set_public_key_der(self, der: bytes) -> None: ...
    def sign(self, der: bytes, digest: str) -> None: ...
    def signature_algorithm(self) -> bytes: ...
    def digest(self, digest: str) -> bytes: ...
    def serial(self) -> tuple[bool, bytes]: ...
    def set_serial(self, value: bytes) -> None: ...
    def time(self, after: bool) -> bytes | None: ...
    def set_time(self, after: bool, time: bytes) -> None: ...
    def adjust_time(self, after: bool, seconds: int) -> None: ...
    def extension_count(self) -> int: ...

class TrustStore:
    def __init__(self) -> None: ...
    def add_certificate_der(self, der: bytes) -> None: ...
    def add_crl_der(self, der: bytes) -> None: ...
    def set_flags(self, flags: int) -> None: ...
    def set_time(self, time: int) -> None: ...
    def load_locations(
        self, file: bytes | None = None, directory: bytes | None = None
    ) -> None: ...
    def verify(self, leaf: bytes, chain: list[bytes]) -> list[bytes]: ...

class TLSWantRead(Exception): ...
class TLSWantWrite(Exception): ...
class TLSWantCertificate(Exception): ...
class TLSClosed(Exception): ...
class TLSSystemError(Exception): ...

def tls_constants() -> dict[str, int]: ...
def tls_capabilities() -> list[str]: ...
def version_description(selector: int) -> bytes: ...
def default_verify_paths() -> tuple[bytes, bytes]: ...

class TLSContext:
    def __init__(self, datagram: bool) -> None: ...
    def verify(self, leaf: bytes, chain: list[bytes]) -> list[bytes]: ...
    def set_verify(self, flags: int) -> None: ...
    def get_verify_mode(self) -> int: ...
    def get_verify_depth(self) -> int: ...
    def set_verify_depth(self, depth: int) -> None: ...
    def get_session_cache_mode(self) -> int: ...
    def set_session_cache_mode(self, value: int) -> int: ...
    def get_timeout(self) -> int: ...
    def set_timeout(self, value: int) -> None: ...
    def set_client_ca_names(self, names: list[bytes]) -> None: ...
    def set_alpn_protocols(self, protocols: list[bytes]) -> None: ...
    def load_verify_locations(
        self, file: bytes | None = None, directory: bytes | None = None
    ) -> None: ...
    def set_min_version(self, version: int) -> None: ...
    def set_max_version(self, version: int) -> None: ...
    def set_options(self, value: int) -> int: ...
    def set_modes(self, value: int) -> int: ...
    def clear_modes(self, value: int) -> int: ...
    def use_certificate_der(self, der: bytes) -> None: ...
    def use_private_key_der(self, der: bytes) -> None: ...
    def add_chain_certificate_der(self, der: bytes) -> None: ...
    def check_private_key(self) -> None: ...
    def add_trusted_certificate_der(self, der: bytes) -> None: ...
    def add_crl_der(self, der: bytes) -> None: ...
    def set_verification_flags(self, value: int) -> None: ...
    def set_verification_time(self, value: int) -> None: ...
    def set_default_verify_paths(self) -> None: ...
    def set_session_id_context(self, value: bytes) -> None: ...
    def add_client_ca_certificate(self, der: bytes) -> None: ...
    def use_dh_parameters_pem(self, pem: bytes) -> None: ...
    def enable_key_logging(self) -> None: ...
    def enable_cookie_callbacks(self) -> None: ...
    def set_cipher_list(self, value: bytes) -> None: ...
    def set_tls13_ciphersuites(self, value: bytes) -> None: ...
    def set_groups(self, value: bytes) -> None: ...
    def set_srtp_profiles(self, value: bytes) -> None: ...

class TLSSession: ...

class TLSConnection:
    def __init__(
        self, context: TLSContext, server: bool, descriptor: int | None = None
    ) -> None: ...
    def info(self) -> dict[str, object]: ...
    def handshake(self, owner: object) -> None: ...
    def shutdown(self, owner: object) -> bool: ...
    def write(
        self, owner: object, data: bytes | bytearray | memoryview
    ) -> int: ...
    def read(self, owner: object, length: int, peek: bool) -> bytes: ...
    def feed_ciphertext(self, data: bytes | bytearray | memoryview) -> int: ...
    def drain_ciphertext(self, length: int) -> bytes: ...
    def dtls_listen(self, owner: object) -> None: ...
    def dtls_handle_timeout(self, owner: object) -> bool: ...
    def dtls_timeout(self) -> float | None: ...
    def session(self) -> TLSSession | None: ...
    def set_session(self, session: TLSSession) -> None: ...
    def set_role(self, server: bool) -> None: ...
    def set_context(self, context: TLSContext) -> None: ...
    def set_verify(self, flags: int) -> None: ...
    def get_verify_mode(self) -> int: ...
    def shutdown_state(self) -> int: ...
    def set_shutdown_state(self, state: int) -> None: ...
    def new_callback_identity(self) -> None: ...
    def set_alpn_protocols(self, protocols: list[bytes]) -> None: ...
    def random(self, server: bool) -> bytes | None: ...
    def master_secret(self) -> bytes | None: ...
    def finished(self, peer: bool) -> bytes: ...
    def exporter(
        self, label: bytes, length: int, context: bytes | None = None
    ) -> bytes: ...
    def certificate(self, peer: bool) -> bytes | None: ...
    def chain(self, verified: bool) -> list[bytes] | None: ...
    def client_ca_names(self) -> list[bytes]: ...
    def input_eof(self) -> None: ...
    def set_options(self, value: int) -> int: ...
    def use_certificate_der(self, der: bytes) -> None: ...
    def use_private_key_der(self, der: bytes) -> None: ...
    def set_ciphertext_mtu(self, value: int) -> None: ...
    def data_mtu(self) -> int: ...
    def request_ocsp(self) -> None: ...
    def pending(self) -> int: ...
    def cipher_names(self) -> list[str]: ...
    def renegotiate(self) -> bool: ...
    def renegotiation_pending(self) -> bool: ...
    def total_renegotiations(self) -> int: ...
    def set_sni(self, value: bytes) -> None: ...
    def set_reference_dns_name(self, value: bytes) -> None: ...

def random_mix(input: bytes) -> None: ...
def random_ready() -> bool: ...
def compiled_version_text() -> str: ...
