name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Sep 17, 2025.
        ref: "5595df3a728dcea01e6d2135b8c509b7331be84a" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Sep 17, 2025.
        ref: "119aa0de18bcc75ce760dc72c6f848daf1446626" # x509-limbo-ref
        persist-credentials: false
