name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Nov 18, 2025.
        ref: "e3c37e9db0f85a762dfcef1642b046bd31090ca4" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Nov 18, 2025.
        ref: "6fb6d88690ec3f37f6892fd8dd7ded3c3cffbf8a" # x509-limbo-ref
        persist-credentials: false
