name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof master branch, as of Mar 27, 2024.
        ref: "507bb993e90a87d0a62591a5284bc34a3f1c5c22" # wycheproof-ref

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Apr 02, 2024.
        ref: "daf8dd36c0f7457d2b9ea006a514b30a4d49b6c1" # x509-limbo-ref
