name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Feb 21, 2026.
        ref: "d544ce0881731f28eaa98e946db430880d216fd5" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Feb 25, 2026.
        ref: "48fa9ab02a19d8755f05591663e94c264f67a5a4" # x509-limbo-ref
        persist-credentials: false
