name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Sep 02, 2025.
        ref: "38a67b11c072a0144da61ec15e5f0c645749c015" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Aug 26, 2025.
        ref: "2e0461d620f766232ebe9a3173aedaa70c52342c" # x509-limbo-ref
        persist-credentials: false
