name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Jan 09, 2026.
        ref: "fca0d3ba9f1286c3af57801ace39c633e29a88f1" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Jan 09, 2026.
        ref: "e6f4018a35924836d622d7d85566f9b5361dbbab" # x509-limbo-ref
        persist-credentials: false
