name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Jun 06, 2026.
        ref: "55239189a3ebaa1b0d993c52ab182eea3adbcd02" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of June 6, 2026.
        ref: "6113d70266602e3bbac25d48f21b2cb15b971b05" # x509-limbo-ref
        persist-credentials: false
