name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Dec 09, 2025.
        ref: "7a774c9c60e25ead4e526619b44221bf1afc464b" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Dec 10, 2025.
        ref: "23c0049f9466a7e325ac8af86d1c66a9f13d70d3" # x509-limbo-ref
        persist-credentials: false
