name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Nov 08, 2025.
        ref: "d043da76bf95b3dbe83bed6ba5fe93f5203ad6fb" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Nov 05, 2025.
        ref: "075fa31aca9155e530ea2caaf3726b104e719613" # x509-limbo-ref
        persist-credentials: false
