name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Oct 26, 2025.
        ref: "b9298df917fbb5b4bfb73bb0dfb1137822b7a098" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Nov 04, 2025.
        ref: "4606b0ff7523adf72cf32b49c5b0f5d50ac96eb2" # x509-limbo-ref
        persist-credentials: false
