name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Feb 20, 2026.
        ref: "8857b886f61118394495621232c03b6a828981bf" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Feb 17, 2026.
        ref: "9a4a64daffeca4918cab0c8b831d6b95b4b87eff" # x509-limbo-ref
        persist-credentials: false
