name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof master branch, as of Apr 06, 2025.
        ref: "3bfb67fca7c7a2ef436e263da53cdabe0fa1dd36" # wycheproof-ref

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Apr 10, 2025.
        ref: "bfe45af9cae556d3297bf8eee60d1c3ce9a64e2b" # x509-limbo-ref
