name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Dec 17, 2025.
        ref: "a92a00302b093944ad321d50ef294cfd41af635b" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Dec 17, 2025.
        ref: "ec08d8da59782f29284b5f23f218198d13e8195d" # x509-limbo-ref
        persist-credentials: false
