name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Jun 26, 2026.
        ref: "ee7b4f7e611928cbe163dc6f5e54527bfd166f34" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Jun 16, 2026.
        ref: "9d41359a05d811ee3de8026ff21d7ddecbd0f3eb" # x509-limbo-ref
        persist-credentials: false
