name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: "C2SP/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof main branch, as of Feb 07, 2026.
        ref: "c441f3ce73ac8d4eedcb4715f2936e0dbd95ddf2" # wycheproof-ref
        persist-credentials: false

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Feb 10, 2026.
        ref: "cb4e66560f72efeb9d10bfe077e909bc2373bfb3" # x509-limbo-ref
        persist-credentials: false
